/**
 * The layer under the interceptors. An interceptor is a gate an agent walks through; this is a wall
 * the kernel holds, so a denied path stays unreadable even to a binary that never saw
 * an interceptor. Generated from the same filesystem policy, so the two cannot disagree.
 */

export const OS_GUARD = {
  /** macOS: a seatbelt profile handed to sandbox-exec. */
  SEATBELT: 'seatbelt',
  /** Linux: Landlock, where the kernel supports it. */
  LANDLOCK: 'landlock',
  /** Nothing available. Reported, never silently treated as protection. */
  NONE: 'none',
} as const;

export type OsGuard = (typeof OS_GUARD)[keyof typeof OS_GUARD];

export interface GuardSupport {
  guard: OsGuard;
  /** Why, in the words `memnox doctor` will print. */
  because: string;
}

/** Landlock landed in 5.13; ABI 3 (the one worth having) in 6.2. */
const LANDLOCK_MINIMUM = { major: 5, minor: 13 };

export function parseKernel(release: string): { major: number; minor: number } | null {
  const match = /^(\d+)\.(\d+)/.exec(release);
  if (match === null) return null;
  return { major: Number(match[1]), minor: Number(match[2]) };
}

export function guardFor(platform: string, kernelRelease: string): GuardSupport {
  if (platform === 'darwin') {
    return {
      guard: OS_GUARD.SEATBELT,
      because: 'macOS can hold a seatbelt profile around the agent',
    };
  }
  if (platform === 'linux') {
    const version = parseKernel(kernelRelease);
    if (version === null) {
      return { guard: OS_GUARD.NONE, because: `kernel "${kernelRelease}" is unreadable` };
    }
    const supported =
      version.major > LANDLOCK_MINIMUM.major ||
      (version.major === LANDLOCK_MINIMUM.major &&
        version.minor >= LANDLOCK_MINIMUM.minor);
    return supported
      ? { guard: OS_GUARD.LANDLOCK, because: `Linux ${kernelRelease} supports Landlock` }
      : {
          guard: OS_GUARD.NONE,
          because: `Linux ${kernelRelease} predates Landlock (needs 5.13+); the interceptors are the only gate`,
        };
  }
  return {
    guard: OS_GUARD.NONE,
    because: `${platform} has no OS guard here; the interceptors are the only gate`,
  };
}

export interface GuardPolicy {
  /** Paths nothing inside the sandbox may read. */
  denyRead: readonly string[];
  /** Paths nothing inside may write. */
  denyWrite: readonly string[];
  /** Directories the agent legitimately works in. */
  allowWrite: readonly string[];
}

function quote(path: string): string {
  return `"${path.replace(/"/g, '\\"')}"`;
}

/**
 * A seatbelt profile, written allow-by-default because a deny-by-default one would
 * have to enumerate everything a compiler touches and would break the first build.
 * The value here is the named paths, which are the ones worth losing.
 */
export function seatbeltProfile(policy: GuardPolicy): string {
  const lines = [
    '(version 1)',
    ';; Generated by Memnox from your filesystem rules. Regenerate rather than edit.',
    '(allow default)',
    '',
  ];
  for (const path of policy.denyRead) {
    lines.push(`(deny file-read* (subpath ${quote(path)}))`);
  }
  for (const path of policy.denyWrite) {
    lines.push(`(deny file-write* (subpath ${quote(path)}))`);
  }
  if (policy.allowWrite.length > 0) {
    lines.push('', ';; Where the work actually happens.');
    for (const path of policy.allowWrite) {
      lines.push(`(allow file-write* (subpath ${quote(path)}))`);
    }
  }
  return `${lines.join('\n')}\n`;
}

/**
 * Landlock is a syscall, not a file, so what ships here is the ruleset a helper would
 * apply. Stated as data so the shape is testable without a kernel.
 */
export interface LandlockRuleset {
  handledAccess: readonly string[];
  rules: { path: string; allow: readonly string[] }[];
}

const READ_ACCESS = ['read_file', 'read_dir'];
const WRITE_ACCESS = ['write_file', 'remove_file', 'remove_dir', 'make_reg'];

export function landlockRuleset(policy: GuardPolicy): LandlockRuleset {
  const denied = new Set([...policy.denyRead, ...policy.denyWrite]);
  return {
    handledAccess: [...READ_ACCESS, ...WRITE_ACCESS],
    rules: [
      // Landlock is allow-list only: grant the roots, then never grant the denied ones.
      ...policy.allowWrite.map((path) => ({
        path,
        allow: [...READ_ACCESS, ...WRITE_ACCESS],
      })),
      ...policy.denyRead
        .filter((path) => !policy.allowWrite.includes(path))
        .map((path) => ({ path, allow: [] as string[] })),
    ].filter((rule) => rule.allow.length > 0 || denied.has(rule.path)),
  };
}

export function sandboxCommand(
  profilePath: string,
  command: readonly string[],
): string[] {
  return ['sandbox-exec', '-f', profilePath, ...command];
}
