/**
 * The kernel's half of an untrusted session: writes only to the repository and temp,
 * credentials and home dotfiles unreadable, and TCP only to the egress proxy. Seatbelt
 * on macOS and Landlock on Linux, both generated here as data so both are testable.
 */
import { join } from 'node:path';

import { MEMNOX_HOME } from '../config/config';
import type { GuardPolicy } from './os-guard';

export interface UntrustedGuard {
  home: string;
  /** Where writes may land: the repository, temp, and the agent's own state. */
  writable: readonly string[];
  /** Dotfiles under the home that stay readable: Memnox's, and where the tools are installed. */
  readable: readonly string[];
  /** Credentials outside the dotfiles, such as the keychains. */
  unreadable: readonly string[];
  /** Inside a writable path and still refused: the rules, and the answers to held calls. */
  unwritable: readonly string[];
  /** The agent's own state, by prefix, since `~/.claude` and `~/.claude.json` are one thing. */
  statePrefixes: readonly string[];
  /** The egress proxy's port, the only TCP destination left. Null leaves TCP alone. */
  proxyPort: number | null;
  /** The repository, whose own key files stay unreadable while a template of names does not. */
  workspace?: string;
}

/** The repository's `.env` files unreadable, its templates of names handed back after. */
function keyFileRules(workspace: string | undefined): string[] {
  if (workspace === undefined) return [];
  const root = literalRegex(workspace);
  return [
    `(deny file-read-data (regex #"^${root}/(.*/)?\\.env(\\.[^/]*)?$"))`,
    `(allow file-read-data (regex #"^${root}/(.*/)?\\.env\\.(example|sample|template)$"))`,
  ];
}

function quote(path: string): string {
  return `"${path.replace(/"/g, '\\"')}"`;
}

/** A path as a seatbelt regex matches it, with every metacharacter taken literally. */
function literalRegex(path: string): string {
  return path.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Allow by default and then the walls, since seatbelt lets a later rule win: dotfiles
 * are refused and then the named few handed back, and writes likewise.
 */
export function untrustedSeatbeltProfile(guard: UntrustedGuard): string {
  const lines = [
    '(version 1)',
    ';; Generated by Memnox for one untrusted session. Regenerated every run.',
    '(allow default)',
    `(deny file-read-data (regex #"^${literalRegex(guard.home)}/\\."))`,
    ...guard.readable.map((path) => `(allow file-read-data (subpath ${quote(path)}))`),
    ...guard.statePrefixes.map(
      (path) => `(allow file-read-data (regex #"^${literalRegex(path)}"))`,
    ),
    ...guard.unreadable.map((path) => `(deny file-read-data (subpath ${quote(path)}))`),
    ...keyFileRules(guard.workspace),
    '(deny file-write*)',
    ...guard.writable.map((path) => `(allow file-write* (subpath ${quote(path)}))`),
    ...guard.statePrefixes.map(
      (path) => `(allow file-write* (regex #"^${literalRegex(path)}"))`,
    ),
    ...guard.unwritable.map((path) => `(deny file-write* (subpath ${quote(path)}))`),
  ];
  if (guard.proxyPort !== null) {
    lines.push(
      '(deny network-outbound)',
      `(allow network-outbound (remote ip "localhost:${guard.proxyPort}"))`,
      // Unix sockets under the Memnox home, which is how a seam reaches the daemon.
      `(allow network-outbound (subpath ${quote(join(guard.home, MEMNOX_HOME))}))`,
    );
  }
  return `${lines.join('\n')}\n`;
}

/** What the Landlock helper applies: access granted beneath each path, nothing elsewhere. */
export interface LandlockPlan {
  /** Read and execute beneath each. */
  read: string[];
  /** Every file access beneath each. */
  write: string[];
  /** The only TCP ports connect reaches, where the kernel can hold it. Null leaves TCP alone. */
  connectPorts: number[] | null;
}

/** One directory entry, as much of it as carving needs. */
export interface CarveEntry {
  name: string;
  /** Skipped, since granting a link would grant wherever it points. */
  symlink: boolean;
}

export type ListDirectory = (dir: string) => readonly CarveEntry[];

/**
 * Landlock only grants, so "everything but ~/.ssh" is spelled as every sibling on the way
 * down to it. Only the ancestors of a denied path are listed, so the walk stays short.
 */
export function carve(
  root: string,
  denied: readonly string[],
  list: ListDirectory,
): string[] {
  if (denied.some((path) => isUnder(root, path))) return [];
  if (!denied.some((path) => isUnder(path, root))) return [root];
  return list(root)
    .filter((entry) => !entry.symlink)
    .flatMap((entry) => carve(join(root, entry.name), denied, list));
}

/** The untrusted session's plan: reads carved around the dotfiles, writes only where named. */
export function untrustedLandlockPlan(
  guard: UntrustedGuard,
  list: ListDirectory,
): LandlockPlan {
  const inHome = list(guard.home).map((entry) => join(guard.home, entry.name));
  // Landlock takes no prefix, so the agent's state is whatever exists under it now.
  const state = inHome.filter((path) =>
    guard.statePrefixes.some((prefix) => path.startsWith(prefix)),
  );
  const keeps = [...guard.readable, ...state];
  const dotfiles = inHome
    .filter((path) => path.startsWith(`${guard.home}/.`))
    .flatMap((path) => deniedBeside(path, keeps, list));
  return {
    read: carve('/', [...dotfiles, ...guard.unreadable], list),
    write: [...guard.writable, ...state].flatMap((path) =>
      carve(path, guard.unwritable, list),
    ),
    connectPorts: guard.proxyPort === null ? null : [guard.proxyPort],
  };
}

/** The plan `protect --os-guard` wrote as rules: reads and writes carved around the denials. */
export function landlockPlanFromPolicy(
  policy: GuardPolicy,
  list: ListDirectory,
): LandlockPlan {
  return {
    read: carve('/', policy.denyRead, list),
    write: carve('/', [...policy.denyRead, ...policy.denyWrite], list),
    connectPorts: null,
  };
}

/**
 * What to refuse under `path` so that every kept path stays reachable: all of it when
 * nothing kept is inside, nothing when it is itself kept, and otherwise its other children.
 */
function deniedBeside(
  path: string,
  keeps: readonly string[],
  list: ListDirectory,
): string[] {
  if (keeps.some((keep) => isUnder(path, keep))) return [];
  if (!keeps.some((keep) => isUnder(keep, path))) return [path];
  return list(path).flatMap((entry) => deniedBeside(join(path, entry.name), keeps, list));
}

/** True for `dir` itself and anything beneath it. */
function isUnder(path: string, dir: string): boolean {
  if (dir === '/') return true;
  return path === dir || path.startsWith(`${dir}/`);
}
