/** Clouds and clusters: where a command changes infrastructure somebody else runs on. */
import { TOOL_CLASS } from '../../discovery/classify';
import { VERB_TAG, type VerbTable } from '../verb-table';

const READ = TOOL_CLASS.READ;
const WRITE = TOOL_CLASS.WRITE;
const GONE = TOOL_CLASS.DESTRUCTIVE;
const SENDS = TOOL_CLASS.COMMUNICATION;
const PROD = VERB_TAG.PRODUCTION;
const SECRETS = VERB_TAG.SECRETS;

export const CLOUD_TABLES: readonly VerbTable[] = [
  {
    name: 'aws',
    credential: ['~/.aws/credentials', '~/.aws/config', 'AWS_ACCESS_KEY_ID'],
    headline: 'can modify infrastructure',
    environmentFlags: ['--profile'],
    environmentVariables: ['AWS_PROFILE'],
    globalFlags: [
      '--profile',
      '--region',
      '--output',
      '--endpoint-url',
      '--query',
      '--color',
    ],
    globalSwitches: ['--debug', '--no-verify-ssl', '--no-paginate', '--no-cli-pager'],
    verbs: [
      { match: 's3 rb **', class: GONE, alternative: 'aws s3 ls, then remove by hand' },
      {
        match: 's3 rm --recursive **',
        class: GONE,
        alternative: 'aws s3 rm one key at a time',
      },
      { match: 'iam delete-**', class: GONE, tags: [SECRETS] },
      { match: 'iam get-**', class: READ, tags: [SECRETS] },
      { match: 'iam list-**', class: READ, tags: [SECRETS] },
      { match: 'iam **', class: WRITE, tags: [SECRETS], note: 'changes who can do what' },
      { match: 'ec2 terminate-instances **', class: GONE },
      { match: 'rds delete-**', class: GONE },
      { match: 'cloudformation delete-stack **', class: GONE },
      {
        match: 'secretsmanager get-secret-value **',
        class: READ,
        tags: [SECRETS],
        note: 'reads a secret value',
      },
      { match: 'sts get-caller-identity', class: READ, note: 'who am I' },
      { match: 's3 ls **', class: READ },
      { match: 's3 presign **', class: READ },
      { match: 's3 rm **', class: GONE },
      {
        match: 's3 cp **',
        class: WRITE,
        note: 'an upload changes the bucket, and argv order is all that says which way',
      },
      { match: 's3 mv **', class: WRITE },
      { match: 's3 sync **', class: WRITE },
      { match: 's3 mb **', class: WRITE },
      // `aws <service> <operation>`: the operation's verb says what it does, whatever the service.
      { match: '* describe-**', class: READ },
      { match: '* list-**', class: READ },
      { match: '* get-**', class: READ },
      { match: '* delete-**', class: GONE },
      { match: '* terminate-**', class: GONE },
      { match: '* create-**', class: WRITE },
      { match: '* put-**', class: WRITE },
      { match: '* update-**', class: WRITE },
      { match: '* modify-**', class: WRITE },
      { match: '* run-**', class: WRITE },
      { match: '* start-**', class: WRITE },
      { match: '* stop-**', class: WRITE },
      { match: '* reboot-**', class: WRITE },
      { match: '* attach-**', class: WRITE },
      { match: '* detach-**', class: WRITE },
      { match: '* associate-**', class: WRITE },
      { match: '* disassociate-**', class: WRITE },
      { match: '* register-**', class: WRITE },
      { match: '* deregister-**', class: WRITE },
      { match: '* add-**', class: WRITE },
      { match: '* remove-**', class: WRITE },
      { match: '* set-**', class: WRITE },
      { match: '* enable-**', class: WRITE },
      { match: '* disable-**', class: WRITE },
      { match: '* tag-**', class: WRITE },
      { match: '* untag-**', class: WRITE },
      { match: '* authorize-**', class: WRITE },
      { match: '* revoke-**', class: WRITE },
      { match: '* restore-**', class: WRITE },
      { match: '* copy-**', class: WRITE },
      { match: '* import-**', class: WRITE },
      { match: '* invoke **', class: WRITE, note: 'runs a function' },
      { match: '* publish **', class: SENDS },
      { match: '* send-**', class: SENDS },
    ],
  },
  {
    name: 'gcloud',
    credential: ['~/.config/gcloud'],
    headline: 'can modify cloud projects',
    environmentFlags: ['--project', '--configuration'],
    environmentVariables: ['CLOUDSDK_CORE_PROJECT', 'CLOUDSDK_ACTIVE_CONFIG_NAME'],
    globalFlags: ['--project', '--account', '--configuration', '--verbosity', '--format'],
    globalSwitches: ['--quiet', '-q'],
    verbs: [
      { match: 'projects delete **', class: GONE },
      { match: 'sql instances delete **', class: GONE },
      { match: 'compute instances delete **', class: GONE },
      { match: 'deploy **', class: WRITE },
      { match: 'auth list', class: READ },
      { match: 'config list', class: READ },
      { match: 'list **', class: READ },
    ],
  },
  {
    name: 'az',
    credential: ['~/.azure/azureProfile.json'],
    headline: 'can modify subscriptions',
    environmentFlags: ['--subscription'],
    globalFlags: ['--subscription', '--output', '-o'],
    globalSwitches: ['--only-show-errors', '--verbose', '--debug'],
    verbs: [
      { match: 'group delete **', class: GONE },
      { match: 'vm delete **', class: GONE },
      { match: 'deployment **', class: WRITE },
      { match: 'account show', class: READ },
      { match: 'list **', class: READ },
    ],
  },
  {
    name: 'kubectl',
    credential: ['~/.kube/config'],
    headline: 'can change what runs in your clusters',
    environmentFlags: ['--context'],
    globalFlags: [
      '--context',
      '--namespace',
      '-n',
      '--kubeconfig',
      '--cluster',
      '--user',
      '-s',
      '--server',
      '--as',
      '--as-group',
      '--request-timeout',
      '-v',
      '--v',
    ],
    globalSwitches: ['--insecure-skip-tls-verify', '-A', '--all-namespaces'],
    verbs: [
      { match: 'delete namespace **', class: GONE },
      { match: 'delete deployment **', class: GONE },
      { match: 'delete pvc **', class: GONE, note: 'takes the volume with it' },
      { match: 'delete **', class: GONE },
      { match: 'drain **', class: GONE },
      { match: 'apply **', class: WRITE },
      { match: 'rollout restart **', class: WRITE },
      { match: 'exec **', class: WRITE, note: 'a shell inside the cluster' },
      { match: 'create **', class: WRITE },
      { match: 'replace **', class: WRITE },
      { match: 'patch **', class: WRITE },
      { match: 'edit **', class: WRITE },
      { match: 'scale **', class: WRITE },
      { match: 'autoscale **', class: WRITE },
      { match: 'set **', class: WRITE },
      { match: 'label **', class: WRITE },
      { match: 'annotate **', class: WRITE },
      { match: 'expose **', class: WRITE },
      { match: 'run **', class: WRITE },
      { match: 'cordon **', class: WRITE },
      { match: 'uncordon **', class: WRITE },
      { match: 'taint **', class: WRITE },
      { match: 'cp **', class: WRITE },
      { match: 'debug **', class: WRITE, note: 'a shell inside the cluster' },
      { match: 'attach **', class: WRITE },
      { match: 'port-forward **', class: WRITE, note: 'opens a way in' },
      { match: 'proxy **', class: WRITE, note: 'opens a way in' },
      { match: 'rollout undo **', class: WRITE },
      { match: 'rollout pause **', class: WRITE },
      { match: 'rollout resume **', class: WRITE },
      { match: 'rollout status **', class: READ },
      { match: 'rollout history **', class: READ },
      { match: 'config view **', class: READ },
      { match: 'config get-contexts **', class: READ },
      { match: 'config current-context', class: READ },
      { match: 'config use-context **', class: WRITE, note: 'local' },
      { match: 'config **', class: WRITE, note: 'local' },
      { match: 'diff **', class: READ },
      { match: 'top **', class: READ },
      { match: 'explain **', class: READ },
      { match: 'events **', class: READ },
      { match: 'api-resources **', class: READ },
      { match: 'api-versions', class: READ },
      { match: 'cluster-info **', class: READ },
      { match: 'version **', class: READ },
      { match: 'auth can-i **', class: READ },
      { match: 'get **', class: READ },
      { match: 'describe **', class: READ },
      { match: 'logs **', class: READ },
    ],
  },
  {
    name: 'terraform',
    credential: ['~/.terraform.d/credentials.tfrc.json'],
    headline: 'can apply infrastructure changes',
    environmentVariables: ['TF_WORKSPACE'],
    globalFlags: ['-chdir='],
    verbs: [
      {
        match: 'destroy **',
        class: GONE,
        alternative: 'terraform plan -destroy, and read it',
      },
      {
        match: 'state rm **',
        class: GONE,
        note: 'the resource survives and is forgotten',
      },
      { match: 'apply **', class: WRITE, alternative: 'terraform plan' },
      { match: 'import **', class: WRITE },
      { match: 'plan **', class: READ },
      { match: 'show **', class: READ },
      { match: 'state mv **', class: WRITE },
      { match: 'state push **', class: WRITE },
      { match: 'state replace-provider **', class: WRITE },
      { match: 'state list **', class: READ },
      { match: 'state show **', class: READ },
      { match: 'state pull **', class: READ },
      { match: 'taint **', class: WRITE },
      { match: 'untaint **', class: WRITE },
      { match: 'force-unlock **', class: WRITE },
      { match: 'workspace delete **', class: GONE },
      { match: 'workspace new **', class: WRITE },
      { match: 'workspace select **', class: WRITE, note: 'local' },
      { match: 'workspace list **', class: READ },
      { match: 'workspace show **', class: READ },
      { match: 'output **', class: READ },
      { match: 'validate **', class: READ },
      { match: 'fmt **', class: WRITE, note: 'local' },
      { match: 'init **', class: WRITE, note: 'local' },
      { match: 'providers **', class: READ },
      { match: 'graph **', class: READ },
      { match: 'version **', class: READ },
    ],
  },
  {
    name: 'docker',
    credential: ['~/.docker/config.json'],
    headline: 'can push images to your registries',
    environmentFlags: ['--context', '-c'],
    environmentVariables: ['DOCKER_CONTEXT'],
    globalFlags: ['--context', '-c', '-H', '--host', '--config', '--log-level', '-l'],
    globalSwitches: ['-D', '--debug', '--tls', '--tlsverify'],
    verbs: [
      { match: 'system prune -a', class: GONE },
      { match: 'rmi -f **', class: GONE },
      { match: 'push **', class: WRITE, tags: [PROD] },
      { match: 'build **', class: WRITE, note: 'local' },
      { match: 'ps **', class: READ },
      { match: 'images **', class: READ },
      { match: 'logs **', class: READ },
      { match: 'inspect **', class: READ },
      { match: 'version **', class: READ },
      { match: 'info **', class: READ },
      { match: 'pull **', class: READ, note: 'local' },
    ],
  },
];
