/** Source, packages and browsers: where a command reaches a repository or a registry. */
import { TOOL_CLASS } from '../../discovery/classify';
import { VERB_TAG, type VerbTable } from '../verb-table';

const READ = TOOL_CLASS.READ;
const WRITE = TOOL_CLASS.WRITE;
const GONE = TOOL_CLASS.DESTRUCTIVE;
const SENDS = TOOL_CLASS.COMMUNICATION;
const PROD = VERB_TAG.PRODUCTION;
const SECRETS = VERB_TAG.SECRETS;

export const CODE_TABLES: readonly VerbTable[] = [
  {
    name: 'gh',
    credential: ['~/.config/gh/hosts.yml', 'GH_TOKEN', 'GITHUB_TOKEN'],
    headline: 'can merge pull requests and delete branches',
    globalFlags: ['-R', '--repo'],
    methodFlags: ['-X', '--method'],
    verbs: [
      { match: 'repo delete **', class: GONE },
      { match: 'release delete **', class: GONE },
      { match: 'issue delete **', class: GONE },
      { match: 'label delete **', class: GONE },
      { match: 'api -X DELETE **', class: GONE },
      { match: 'api --method DELETE **', class: GONE },
      { match: 'api -X POST **', class: WRITE },
      { match: 'api -X PUT **', class: WRITE },
      { match: 'api -X PATCH **', class: WRITE },
      { match: 'api --method POST **', class: WRITE },
      { match: 'api --method PUT **', class: WRITE },
      { match: 'api --method PATCH **', class: WRITE },
      // A field makes `gh api` send a POST unless a method says otherwise.
      { match: 'api -f **', class: WRITE, note: 'a field is sent as a POST' },
      { match: 'api -F **', class: WRITE, note: 'a field is sent as a POST' },
      { match: 'api --field **', class: WRITE, note: 'a field is sent as a POST' },
      { match: 'api --raw-field **', class: WRITE, note: 'a field is sent as a POST' },
      { match: 'api --input **', class: WRITE, note: 'a body is sent as a POST' },
      { match: 'api -X GET **', class: READ },
      { match: 'api --method GET **', class: READ },
      { match: 'api -X HEAD **', class: READ },
      { match: 'api --method HEAD **', class: READ },
      // Refined by the query text: a mutation is a write, anything else reads.
      { match: 'api graphql **', class: READ, note: 'a GraphQL query reads' },
      {
        match: 'pr merge **',
        class: WRITE,
        alternative: 'gh pr view, and let a person merge',
      },
      {
        match: 'pr review --approve **',
        class: WRITE,
        note: 'an approval is what lets a merge through',
        alternative: 'gh pr review --comment, and let a person approve',
      },
      {
        match: 'pr review -a **',
        class: WRITE,
        note: 'an approval is what lets a merge through',
      },
      { match: 'pr checkout **', class: WRITE, note: 'local' },
      { match: 'pr lock **', class: WRITE },
      { match: 'pr unlock **', class: WRITE },
      { match: 'issue transfer **', class: WRITE },
      { match: 'issue pin **', class: WRITE },
      { match: 'issue unpin **', class: WRITE },
      { match: 'issue lock **', class: WRITE },
      { match: 'issue develop **', class: WRITE },
      { match: 'release edit **', class: WRITE },
      { match: 'release upload **', class: WRITE },
      { match: 'repo fork **', class: WRITE },
      { match: 'repo rename **', class: WRITE },
      { match: 'repo archive **', class: WRITE },
      { match: 'repo sync **', class: WRITE },
      { match: 'repo clone **', class: READ, note: 'a local copy' },
      { match: 'repo list **', class: READ },
      { match: 'workflow enable **', class: WRITE },
      { match: 'workflow disable **', class: WRITE },
      { match: 'workflow view **', class: READ },
      { match: 'run delete **', class: GONE },
      { match: 'run download **', class: READ },
      { match: 'run watch **', class: READ },
      { match: 'cache delete **', class: GONE },
      { match: 'cache list **', class: READ },
      { match: 'secret delete **', class: GONE, tags: [SECRETS] },
      { match: 'secret list **', class: READ, tags: [SECRETS], note: 'names only' },
      { match: 'variable set **', class: WRITE },
      { match: 'variable delete **', class: GONE },
      { match: 'variable list **', class: READ },
      { match: 'variable get **', class: READ },
      { match: 'label edit **', class: WRITE },
      { match: 'label list **', class: READ },
      { match: 'gist delete **', class: GONE },
      { match: 'gist edit **', class: WRITE },
      { match: 'gist view **', class: READ },
      { match: 'gist list **', class: READ },
      { match: 'ruleset list **', class: READ },
      { match: 'ruleset view **', class: READ },
      { match: 'ruleset check **', class: READ },
      { match: 'search **', class: READ },
      { match: 'browse **', class: READ },
      { match: 'status **', class: READ },
      { match: 'project list **', class: READ },
      { match: 'project view **', class: READ },
      { match: 'project item-list **', class: READ },
      { match: 'project **', class: WRITE, note: 'edits a project board' },
      { match: 'codespace list **', class: READ },
      { match: 'codespace delete **', class: GONE },
      { match: 'codespace **', class: WRITE },
      { match: 'auth token **', class: READ, tags: [SECRETS], note: 'prints the token' },
      { match: 'auth login **', class: WRITE, tags: [SECRETS] },
      { match: 'auth logout **', class: WRITE },
      { match: 'release create **', class: WRITE, tags: [PROD] },
      { match: 'secret set **', class: WRITE, tags: [SECRETS] },
      { match: 'repo edit **', class: WRITE },
      { match: 'pr create **', class: WRITE, note: 'opens a PR, merges nothing' },
      { match: 'pr close **', class: WRITE },
      { match: 'pr reopen **', class: WRITE },
      { match: 'pr comment **', class: SENDS },
      { match: 'pr review **', class: SENDS },
      { match: 'pr edit **', class: WRITE },
      { match: 'pr ready **', class: WRITE },
      { match: 'issue create **', class: WRITE },
      { match: 'issue close **', class: WRITE },
      { match: 'issue reopen **', class: WRITE },
      { match: 'issue edit **', class: WRITE },
      { match: 'issue comment **', class: SENDS },
      { match: 'workflow run **', class: WRITE },
      { match: 'run rerun **', class: WRITE },
      { match: 'run cancel **', class: WRITE },
      { match: 'repo create **', class: WRITE },
      { match: 'label create **', class: WRITE },
      { match: 'gist create **', class: WRITE },
      { match: 'auth status', class: READ },
      { match: 'pr view **', class: READ },
      { match: 'pr list **', class: READ },
      { match: 'pr diff **', class: READ },
      { match: 'pr checks **', class: READ },
      { match: 'pr status **', class: READ },
      { match: 'issue view **', class: READ },
      { match: 'issue list **', class: READ },
      { match: 'run view **', class: READ },
      { match: 'run list **', class: READ },
      { match: 'workflow list **', class: READ },
      { match: 'repo view **', class: READ },
      { match: 'release list **', class: READ },
      {
        match: 'api **',
        class: READ,
        note: 'a GET unless a method or a field says otherwise',
      },
    ],
  },
  {
    name: 'git',
    credential: ['~/.git-credentials', '~/.netrc'],
    headline: 'can push to your repositories',
    globalFlags: ['-C', '-c', '--git-dir', '--work-tree', '--namespace', '--exec-path='],
    globalSwitches: [
      '--no-pager',
      '-p',
      '--paginate',
      '--bare',
      '--no-replace-objects',
      '-P',
      // Editors and agents poll with this one, so without it every background status is unknown.
      '--no-optional-locks',
      '--literal-pathspecs',
      '--glob-pathspecs',
      '--noglob-pathspecs',
      '--icase-pathspecs',
      '--no-lazy-fetch',
      '--no-advice',
    ],
    verbs: [
      {
        match: 'push --force **',
        class: GONE,
        alternative: 'push a branch and open a PR',
        note: 'rewrites history somebody may have pulled',
      },
      { match: 'push -f **', class: GONE, alternative: 'push a branch and open a PR' },
      { match: 'reset --hard **', class: GONE, note: 'discards uncommitted work' },
      { match: 'branch -D **', class: GONE },
      { match: 'clean -fd **', class: GONE },
      { match: 'clean -f **', class: GONE, note: 'deletes untracked files' },
      { match: 'push **', class: WRITE },
      { match: 'commit **', class: WRITE, note: 'local' },
      { match: 'add **', class: WRITE, note: 'local' },
      { match: 'rm **', class: WRITE, note: 'local' },
      { match: 'mv **', class: WRITE, note: 'local' },
      { match: 'merge **', class: WRITE, note: 'local' },
      { match: 'rebase **', class: WRITE, note: 'rewrites local history' },
      { match: 'cherry-pick **', class: WRITE, note: 'local' },
      { match: 'revert **', class: WRITE, note: 'local' },
      { match: 'am **', class: WRITE, note: 'local' },
      { match: 'apply **', class: WRITE, note: 'local' },
      { match: 'checkout **', class: WRITE, note: 'local' },
      { match: 'switch **', class: WRITE, note: 'local' },
      { match: 'restore **', class: WRITE, note: 'local' },
      { match: 'stash **', class: WRITE, note: 'local' },
      { match: 'stash list **', class: READ },
      { match: 'stash show **', class: READ },
      { match: 'tag **', class: WRITE, note: 'local' },
      { match: 'tag -l **', class: READ },
      { match: 'tag --list **', class: READ },
      { match: 'tag $', class: READ, name: 'tag-list' },
      { match: 'branch **', class: WRITE, note: 'local' },
      { match: 'branch $', class: READ, name: 'branch-list' },
      { match: 'branch -a **', class: READ },
      { match: 'branch -r **', class: READ },
      { match: 'branch -v **', class: READ },
      { match: 'branch --list **', class: READ },
      { match: 'branch --show-current', class: READ },
      { match: 'pull **', class: WRITE, note: 'changes the working tree' },
      { match: 'init **', class: WRITE, note: 'local' },
      { match: 'worktree **', class: WRITE, note: 'local' },
      { match: 'worktree list **', class: READ },
      { match: 'config **', class: WRITE, note: 'local' },
      { match: 'config --get **', class: READ },
      { match: 'config --get-all **', class: READ },
      { match: 'config --get-regexp **', class: READ },
      { match: 'config --list **', class: READ },
      { match: 'config -l **', class: READ },
      { match: 'remote **', class: WRITE, note: 'local' },
      { match: 'remote -v', class: READ },
      { match: 'remote $', class: READ, name: 'remote-list' },
      { match: 'remote show **', class: READ },
      { match: 'remote get-url **', class: READ },
      { match: 'fetch **', class: READ, note: 'downloads, changes no branch' },
      { match: 'clone **', class: READ, note: 'a local copy' },
      { match: 'status **', class: READ },
      { match: 'log **', class: READ },
      { match: 'diff **', class: READ },
      { match: 'show **', class: READ },
      { match: 'blame **', class: READ },
      { match: 'grep **', class: READ },
      { match: 'ls-files **', class: READ },
      { match: 'ls-tree **', class: READ },
      { match: 'ls-remote **', class: READ },
      { match: 'rev-parse **', class: READ },
      { match: 'rev-list **', class: READ },
      { match: 'describe **', class: READ },
      { match: 'shortlog **', class: READ },
      { match: 'reflog **', class: READ },
      { match: 'cat-file **', class: READ },
      { match: 'merge-base **', class: READ },
      { match: 'name-rev **', class: READ },
      { match: 'for-each-ref **', class: READ },
      { match: 'whatchanged **', class: READ },
      { match: 'range-diff **', class: READ },
      { match: 'version', class: READ },
      { match: 'help **', class: READ },
    ],
  },
  {
    name: 'npm',
    credential: ['~/.npmrc', 'NPM_TOKEN'],
    headline: 'can publish packages',
    globalFlags: ['--prefix', '--workspace', '-w', '--registry', '--userconfig'],
    globalSwitches: [
      '-g',
      '--global',
      '-s',
      '--silent',
      '-y',
      '--yes',
      '--workspaces',
      '-ws',
    ],
    verbs: [
      { match: 'unpublish **', class: GONE },
      {
        match: 'publish **',
        class: WRITE,
        tags: [PROD],
        note: 'everyone can install it',
      },
      { match: 'deprecate **', class: WRITE, tags: [PROD] },
      { match: 'dist-tag add **', class: WRITE, tags: [PROD] },
      { match: 'dist-tag rm **', class: WRITE, tags: [PROD] },
      { match: 'dist-tag ls **', class: READ },
      { match: 'owner add **', class: WRITE },
      { match: 'owner rm **', class: WRITE },
      { match: 'owner ls **', class: READ },
      { match: 'access **', class: WRITE },
      { match: 'token **', class: WRITE, tags: [SECRETS] },
      { match: 'install **', class: WRITE, note: 'runs install scripts' },
      { match: 'i **', class: WRITE, note: 'runs install scripts' },
      { match: 'add **', class: WRITE, note: 'runs install scripts' },
      { match: 'ci **', class: WRITE, note: 'runs install scripts' },
      { match: 'update **', class: WRITE, note: 'runs install scripts' },
      { match: 'rebuild **', class: WRITE, note: 'runs install scripts' },
      { match: 'uninstall **', class: WRITE },
      { match: 'remove **', class: WRITE },
      { match: 'audit fix **', class: WRITE, note: 'changes the lockfile' },
      { match: 'dedupe **', class: WRITE },
      { match: 'prune **', class: WRITE },
      { match: 'link **', class: WRITE },
      { match: 'pkg set **', class: WRITE },
      { match: 'pkg delete **', class: WRITE },
      { match: 'version **', class: WRITE, note: 'bumps and tags' },
      { match: 'init **', class: WRITE },
      { match: 'exec **', class: WRITE, note: 'runs a package' },
      { match: 'x **', class: WRITE, note: 'runs a package' },
      { match: 'run **', class: WRITE },
      { match: 'run-script **', class: WRITE },
      { match: 'test **', class: WRITE, note: 'runs a script' },
      { match: 'start **', class: WRITE, note: 'runs a script' },
      { match: 'ls **', class: READ },
      { match: 'list **', class: READ },
      { match: 'view **', class: READ },
      { match: 'info **', class: READ },
      { match: 'show **', class: READ },
      { match: 'outdated **', class: READ },
      { match: 'audit **', class: READ },
      { match: 'search **', class: READ },
      { match: 'explain **', class: READ },
      { match: 'why **', class: READ },
      { match: 'query **', class: READ },
      { match: 'pkg get **', class: READ },
      { match: 'config get **', class: READ },
      { match: 'config list **', class: READ },
      { match: 'config **', class: WRITE, note: 'local' },
      { match: 'whoami **', class: READ },
      { match: 'ping **', class: READ },
      { match: 'doctor **', class: READ },
      { match: 'pack **', class: READ, note: 'a local tarball' },
      { match: 'help **', class: READ },
      { match: 'root **', class: READ },
      { match: 'prefix **', class: READ },
    ],
  },
  {
    name: 'playwright',
    credential: [],
    headline: 'can act on websites as you',
    verbs: [
      { match: 'test **', class: WRITE, note: 'drives a browser' },
      { match: '**', class: WRITE, note: 'drives a browser' },
    ],
  },
];
